-- Smart planning: AI-generated blocks are stored as schedule_events with
-- source = 'plan' so they appear in the dashboard and calendar alongside
-- manual and Google events, and can be regenerated by replacing just the
-- 'plan' rows.

alter table public.schedule_events drop constraint if exists schedule_events_source_check;
alter table public.schedule_events
  add constraint schedule_events_source_check check (source in ('manual', 'google', 'plan'));
